# Generated by Django 3.0.3 on 2021-02-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20210228_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='num_page',
            field=models.IntegerField(default=0),
        ),
    ]
