# Generated by Django 3.0.3 on 2021-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_auto_20210228_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='thumbnail_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='cdn_url',
            field=models.URLField(default=None),
        ),
    ]
