# Generated by Django 3.0.3 on 2021-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20210228_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='code',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
