# Generated by Django 3.0.3 on 2021-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_auto_20210228_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
