# Generated by Django 3.0.3 on 2021-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_auto_20210228_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.CharField(default=None, max_length=30, null=True, unique=True),
        ),
    ]
