# Generated by Django 3.0.3 on 2021-02-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_auto_20210228_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='code',
            new_name='chapter_code',
        ),
    ]
