# Generated by Django 3.0.3 on 2021-02-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_auto_20210228_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='code',
        ),
    ]
