# Generated by Django 3.0.3 on 2021-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_auto_20210228_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
