# Generated by Django 3.0.3 on 2021-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_chapter_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
